# Generated by Django 5.0.4 on 2024-04-06 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_rename_module_id_moduleyear_module'),
        ('teacher', '0002_teacher_experience_teacher_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
