# Generated by Django 5.0.4 on 2024-04-04 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0002_yearsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('year_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.yearsection')),
            ],
        ),
    ]
