# Generated by Django 5.0.4 on 2024-04-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.module'),
        ),
    ]
