# Generated by Django 5.0.2 on 2024-03-03 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('section', '0001_initial'),
        ('year', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='year.year')),
            ],
        ),
    ]
