# Generated by Django 5.0.2 on 2024-02-26 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('contactNumber', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('joinDate', models.DateField()),
                ('collegeMail', models.EmailField(max_length=254)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.baseuser',),
        ),
    ]
