# Generated by Django 5.0.2 on 2024-03-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
