# Generated by Django 4.2 on 2024-03-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_baseuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/img/'),
        ),
    ]
